### ISSUE TITLE
request.env["omniauth.auth"] is nil when using Javascript SDK

### ISSUE THREAD

**Issue by andrewhavens** [simi/omniauth-facebook#229]
I'm using the Facebook Javascript SDK to perform login, just like in the Sinatra example. I make a request to my `/auth/facebook/callback`, but `request.env["omniauth.auth"]` is nil. The readme says that it is supposed to parse the signed request cookie. I have confirmed that the cookie is being set. I was able to verify that the access token is valid too. But for some reason, omniauth-facebook is not setting the data in the omniauth hash. Is this a bug? Or is there something that I'm doing wrong?

**Comment by andrewhavens** [comment]
When I use the redirect method (visit `/auth/facebook`) it is set correctly. However, in my case, I must use the Facebook Javascript SDK.

**Comment by izoomi** [comment]
+1 any update on this?

**Comment by dmcbrayer** [comment]
+1 ditto.  I am having the exact same issue.

**Comment by aledalgrande** [comment]
Found any solution? +1

**Comment by algodave** [comment]
Same issue here, any update?

**Comment by mkdynamic** [comment]
Are you seeing any errors? I noticed when testing that FB only does not appear to set the required FBSR_ cookie when the host was `localhost:9292`, but works when I use Pow and use a non localhost domain with no port `omniauth-facebook.dev`. Are you seeing this on localhost domains? With ports?

**Comment by sophiez2628** [comment]
i also notice that there is no 'Callback phase initiated' in my logs. what is causing the problem?

**Comment by mmahalwy** [comment]
any update on this?

**Comment by asok** [comment]
It seems I have the same issue.

> Are you seeing any errors?

Where can I find the http request done by the gem? I did add to the initializer: `OmniAuth.config.logger = Rails.logger` but I don't see anything in the logs.

**Comment by renchap** [comment]
If the `FBSR_cookie` is not set, it is most probably because your App Domain (on the Facebook Developer website) is wrong and/or you are using `localhost`.
If your app is on `localhost` (with any port), you need to have an empty App Domain setting (source: https://stackoverflow.com/a/7493806/1377358).
If you have, for example, `http://localhost` as I did, the FB SDK will try to set the cookie with a `.localhost` domain, which will silently fail.

**Comment by dminchev** [comment]
[Solved]
After spending a few hours debugging different applications that I've previously implemented the omniauth with devise I found the solutions - you have to keep the callback path as showed default in the documentation:  **/auth/facebook/callback/** otherwise the request.env["omniauth.auth"] will be nill

**Comment by yuvi17** [comment]
@andrewhavens can this be closed if the solutions suggested by @dminchev worked? cc: @simi

**Comment by andrewhavens** [comment]
@yuvi17 I'm not convinced that @dminchev's solution is related to the original issue, considering his solution is what I mentioned in my original post. It's been a long time since I've looked at this. Has anyone tried to reproduce this recently using the Facebook Javascript SDK?

**Comment by mtoribio** [comment]
I've found the same problem...

```
$scope.facebookLogin = function() {
    console.debug('facebookLogin Clicked!');
    FB.login((login_response) => {
      console.debug('FB.login called', login_response);
      if (login_response.authResponse) {
        $http.get('/user/spree_user/auth/facebook/callback').then((callback_response) => {
          debugger
          console.debug('FB.callback response', callback_response);
        });
      }
    });
};
```
with this, `request.env["omniauth.auth"]` is `nil`

If I use the server-flow it's works
