### ISSUE TITLE
Processing of routes with a variable scope

### ISSUE THREAD

**Issue by eduardobarbiero** [simi/omniauth-facebook#287]
Hello!

I encountered a problem when implementing the gem, because I use a "dummy path per company", that is, I have a url:

Ex: http://localhost:3000/vetor-saude/auth/facebook

However, gem is not recognizing that "vetor-saude" is my business identifier by route scope.

Is there any way around this problem? being sending a parameter via query or even injecting the same in the callback? I use this identifier to identify which company the user is in.

route:

```ruby
scope ":company_id" do
    resources :auth, path: "autorizar" do
      get :callback, to: 'auth#oauth_create'

      collection do
        get 'failure', to: redirect('/')
      end
    end
end
```

Thanks!

**Comment by abhinaykumar** [comment]
Instead of changing the defaults, i would suggest try something like passing the name of the company as params while making a request or save it in session variable.

*  To pass `params` while making a request to provider like `facebook` 
code should look like this: 
```
omniauth_authorize_path(:user, :facebook, company: 'name')
```
and in url callback you'll get these params. for more information regarding how you can access these params please take a look at this question/answer: https://stackoverflow.com/questions/9890985/passing-parameters-through-omniauth

* To set session variable something like this: 

```
session["devise.company"] = name_of_the_company
```
and call the same inside respective method in `omniauth_callback_controller.rb` 

sample code could look like:

```
def facebook
  company = session["devise.company"]
  user = User.from_omniauth(request.env["omniauth.auth"], company)
  :
  :
end
