### ISSUE TITLE
New maintainer proposal

### ISSUE THREAD

**Issue by pboling** [simi/omniauth-facebook#375]
I maintain the oauth2 gem which is a dependency of this gem (by way of omniauth-oauth2), and _would like to be a maintainer here as well_.

I am working a new *major* release of the `oauth2` gem (v2.0.0), which will have a number of potential breaking changes.     I want to do what I can to ensure other major gems, with millions of downloads and implementations, that depend on `oauth2` don't die horrible fiery deaths or inundate issue trackers.  I might even be able to figure out ways to unbreak [some of the soon-to-be-released changes](https://github.com/oauth-xx/oauth2/blob/master/CHANGELOG.md#unreleased).

Would love to help out, and particularly focus on the maintaining the integration with the underlying `oauth2` lib.

**Comment by simi** [comment]
Hello, I'm trying to actively maintain this gem. Feel free to ping me with news in `oauth2` gem and open draft PR once ready. If you would like to help maintaining this gem, feel free to. Usually it is about issue triage and updating to latest valid API endpoint. This gem is otherwise pretty stable and there are no requests for new features. The only pending feature is https://github.com/simi/omniauth-facebook/pull/315, which is still missing some kind of security review.

If you need any additional access, feel free to ping me. I can take a look. Thanks for your interest.
